// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include <ngrest/common/Service.h>
#include <list>

#include "Contact.h"

//! Phonebook service
/*! Phonebook service to manage contacts */
// *location: phonebook
class RestServer : public ngrest::Service
{
public:
    //! Get a contact by id
    // *method: GET
    Contact read(const std::string& name);

    //! Gets all contacts
    // *method: GET
    std::list<Contact> readAll();

    //! Adds a new contact
    // *method: POST
    void create(const std::string& name, const std::string& number);

    //! Edits a contact
    // *method: PUT
    void update(const std::string& id, const std::string& name, const std::string& number);

    //! Deletes a contact by name
    // *method: DELETE
    void remove(const std::string& id);

    //! Sign in to an account
    // *method: GET
    std::string signIn(const std::string& username, const std::string& password, const std::string& key);

    //! Sign up to an account
    // *method: GET
    void signUp(const std::string& username, const std::string& password, const std::string& key);
};
