// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "RestServer.h"

#include "Phonebook.h"

std::list<Contact> RestServer::readAll() {
    return phonebook::readAll();
}

Contact RestServer::read(const std::string& id) {
    return phonebook::read(id);
}

void RestServer::create(const std::string& name, const std::string& number) {
    phonebook::create(Contact{name, number});
}

void RestServer::update(const std::string& id, const std::string& name, const std::string& number) {
    phonebook::update(id, Contact{name, number});
}

void RestServer::remove(const std::string& id) {
    phonebook::remove(id);
}

std::string RestServer::signIn(const std::string& username, const std::string& password, const std::string& key) {
    return phonebook::signIn(AuthBundle{username, password, key});
}

void RestServer::signUp(const std::string& username, const std::string& password, const std::string& key) {
    phonebook::signUp(AuthBundle{username, password, key});
}
